# app/config/security.yml
security:
  firewalls:
    secured_area:
      pattern: ^/
      anonymous: ~
      http_basic:
        realm: "Area Segura"

  access_control:
    - { path: ^/plancompras/*, roles: 'ROLE_USER' }
    - { path: ^/producto/*, roles: 'IS_AUTHENTICATED_FULLY' }
      
  providers:
    in_memory:
      users:
        gestor: { password: universo, roles: 'ROLE_USER' }
        admin: { password: adm1n, roles: 'ROLE_ADMIN' }
        
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    
  acl:
    connection: default

