<?php

namespace Salud\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecificoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecificoRepository extends EntityRepository
{
}