<?php

namespace Salud\ComprasBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EspecificoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EspecificoRepository extends EntityRepository
{
    public function getByCatalogo($catalogo) {
        $qb = $this->createQueryBuilder('e')
                ->orderBy('e.descripcionespecifico')
                ->join('e.idCatalogoProducto', 'c')
                ->where('c.codigocatalogo = :catalogo_producto')
                ->setParameter('catalogo_producto', $catalogo)
                ;
        return $qb;
    }
}